import test from 'node:test';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {TerrainController,navCommand} from '../src/core/terrain-controller.ts';

test('terrain math matches 59 snapshots generated by the original C++ adapter',async()=>{
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/terrain-contract-golden.json',import.meta.url),'utf8'));
const c=new TerrainController();
let maxAbsError=0, scalarComparisons=0;
function close(actual,expected,path,tolerance=1e-6) {
  if(Array.isArray(expected)) {
    assert.equal(actual.length,expected.length,`${path}: array length`);
    expected.forEach((value,i)=>close(actual[i],value,`${path}[${i}]`,tolerance));
  } else if(typeof expected==='number') {
    assert(Number.isFinite(actual),`${path}: nonfinite ${actual}`);
    const diff=Math.abs(actual-expected);
    maxAbsError=Math.max(maxAbsError,diff);scalarComparisons++;
    assert(diff<=tolerance,`${path}: actual=${actual}, expected=${expected}, abs=${diff}`);
  } else assert.equal(actual,expected,path);
}

for(const r of fixture.records) {
  const e=r.expected;
  const mapped=navCommand(r.rawCommand);
  close(mapped,r.command,`${r.name}.command`);
  let effort=Array(6).fill(0);
  const networks={encode:async()=>Float32Array.from(r.mockLatent),act:async()=>Float32Array.from(r.mockAction)};
  if(r.operation==='reset') c.reset();
  else {
    if(r.operation==='ready_tick')c.setMode('ready');
    else if(r.operation==='off_tick')c.setMode('off');
    else c.setMode('policy');
    assert(c.tick<e.tick,`${r.name}: nonincreasing tick`);
    while(c.tick<e.tick)effort=await c.update(r.state,mapped,networks);
  }
  const actual={
    observation:Array.from(c.actor.slice(0,30)),actor:Array.from(c.actor),
    history:Array.from(c.history),input:Array.from(c.input),
    rawAction:Array.from(c.rawAction),action:Array.from(c.action),effort,
    phase:c.phase,tick:c.tick,inferenceCount:c.inferenceCount,ready:c.ready,
    mode:{off:0,ready:1,policy:2}[c.mode],
  };
  for(const key of Object.keys(actual))close(actual[key],e[key],`${r.name}.${key}`);
}
console.log(JSON.stringify({status:'PASS',records:fixture.records.length,scalarComparisons,maxAbsError,sourceCommit:fixture.sourceCommit},null,2));

});
